- name: test requirements
  hosts: localhost
  collections:
  - awx.awx
  tasks:
  - name: Copy tower project
    tower_project:
      name: copy
      copy_from: second_repo
      description: Foo copy project
      organization: Default
      state: present
